export const ROUTES = {
  HOME: "/dashboard",
  EDITORIAL_MERIT: "/dashboard/apps/editorial-merit",
  TEMPLATES: "/dashboard/apps/templates",
  TEMPLATES_INVERTED_PYRAMID: "/dashboard/apps/templates/inverted-pyramid",
  TEMPLATES_MODERATE_PYRAMID: "/dashboard/apps/templates/moderate-pyramid",
  TEMPLATES_HOURGLASS: "/dashboard/apps/templates/hourglass",
  TEMPLATES_DIAMOND: "/dashboard/apps/templates/diamond",
  TEMPLATES_KEBAB: "/dashboard/apps/templates/kebab",
  TEMPLATES_MARTINI: "/dashboard/apps/templates/martini",
  BREAKING_NEWS: "/dashboard/apps/breaking-news",
  HEADLINES: "/dashboard/apps/headlines",
  PRESS_REPORT: "/dashboard/apps/press-report",
  FIVE_NEEDS: "/dashboard/apps/five-needs",
  COVERAGE: "/dashboard/apps/coverage",
  COVERAGE_FIVE_BOXES: "/dashboard/apps/coverage/five-boxes",
} as const;
