import {
  HiOutlineScale,
  HiOutlineTemplate,
  HiOutlineLightningBolt,
  HiOutlinePencilAlt,
  HiOutlineDocumentText,
  HiOutlineHand,
  HiOutlineVideoCamera,
} from "react-icons/hi";
import type { AppItem } from "@/types/tools";

export const apps: AppItem[] = [
  {
    title: "الجدارة التحريرية",
    description: "تقييم مدى أهمية الخبر واستحقاقه للنشر وفق معايير الجدارة التحريرية",
    href: "/dashboard/apps/editorial-merit",
    icon: HiOutlineScale,
    color: "from-brand-500 to-brand-400",
  },
  {
    title: "القوالب الصحفية",
    description: "تحليل بنية النص وفق القوالب الصحفية الستة المعتمدة",
    href: "/dashboard/apps/templates",
    icon: HiOutlineTemplate,
    color: "from-indigo-500 to-indigo-400",
    children: [
      {
        title: "الهرم المقلوب",
        description: "ترتيب المعلومات من الأهم إلى الأقل أهمية",
        href: "/dashboard/apps/templates/inverted-pyramid",
        icon: HiOutlineTemplate,
        color: "",
      },
      {
        title: "الهرم المعتدل",
        description: "التدرج المتوازن في عرض المعلومات",
        href: "/dashboard/apps/templates/moderate-pyramid",
        icon: HiOutlineTemplate,
        color: "",
      },
      {
        title: "الساعة الرملية",
        description: "الجمع بين الهرم المقلوب والسرد القصصي",
        href: "/dashboard/apps/templates/hourglass",
        icon: HiOutlineTemplate,
        color: "",
      },
      {
        title: "الماسة الإخبارية",
        description: "البدء بملخص ثم التوسع والعودة للتركيز",
        href: "/dashboard/apps/templates/diamond",
        icon: HiOutlineTemplate,
        color: "",
      },
      {
        title: "سيخ الكباب",
        description: "ربط عناصر الخبر بمحور مركزي واحد",
        href: "/dashboard/apps/templates/kebab",
        icon: HiOutlineTemplate,
        color: "",
      },
      {
        title: "كأس المارتيني",
        description: "الانطلاق من العام إلى التفاصيل الدقيقة",
        href: "/dashboard/apps/templates/martini",
        icon: HiOutlineTemplate,
        color: "",
      },
    ],
  },
  {
    title: "الأخبار العاجلة",
    description: "تقييم مدى ملاءمة الخبر لمعايير الأخبار العاجلة والتغطية الفورية",
    href: "/dashboard/apps/breaking-news",
    icon: HiOutlineLightningBolt,
    color: "from-red-500 to-orange-400",
  },
  {
    title: "العناوين",
    description: "تحليل جودة العناوين الصحفية وفعاليتها في جذب القارئ",
    href: "/dashboard/apps/headlines",
    icon: HiOutlinePencilAlt,
    color: "from-amber-500 to-yellow-400",
  },
  {
    title: "التقرير الصحفي",
    description: "تقييم شامل لجودة التقرير الصحفي من حيث البنية والمحتوى والمصادر",
    href: "/dashboard/apps/press-report",
    icon: HiOutlineDocumentText,
    color: "from-emerald-500 to-teal-400",
  },
  {
    title: "الاحتياجات الخمسة",
    description: "التحقق من اكتمال عناصر الخبر الأساسية: من، ماذا، أين، متى، لماذا",
    href: "/dashboard/apps/five-needs",
    icon: HiOutlineHand,
    color: "from-cyan-500 to-blue-400",
  },
  {
    title: "أصول التغطية الصحفية",
    description: "تحليل أساليب وقوالب التغطية الصحفية الميدانية والمهنية",
    href: "/dashboard/apps/coverage",
    icon: HiOutlineVideoCamera,
    color: "from-purple-500 to-pink-400",
    children: [
      {
        title: "الصناديق الخمسة",
        description: "تقسيم التغطية إلى خمسة صناديق منهجية",
        href: "/dashboard/apps/coverage/five-boxes",
        icon: HiOutlineVideoCamera,
        color: "",
      },
    ],
  },
];
